### ISSUE TITLE
i am disabled and can't press f9

### ISSUE THREAD

**Issue by weeLzy** [rlevet/dbd-autostruggle#1]
would it be possible for you to change to space key?

**Comment by azalty** [comment]
Hi!
Sorry for the late answer :-/

I can't bind the space key to emulate the space key
- In case your "struggle key" isn't space bar, tell me which key it is
- In case your "struggle key" is space bar, choose another key to start emulating space bar

**Comment by weeLzy** [comment]
can you make 'c' emulate space bar?

**Comment by azalty** [comment]
Ok, I will do this asap

**Comment by azalty** [comment]
Done!
See: https://github.com/rlevet/dbd-autostruggle/tree/master/experimental/c
Direct download link: https://github.com/rlevet/dbd-autostruggle/raw/master/experimental/c/%5BC%5D%20DBD_Autostruggle.1.0.0.exe

Tell me if it works

**Comment by weeLzy** [comment]
I really appreciate it!!! works like a charm!

**Comment by azalty** [comment]
Haha thanks!
Have fun!
